#!/bin/bash

# check if the namespace command and name were given
if [[ "$1" == "" ]] || [[ "$2" == "" ]]; then
    echo "► No target namespace given"
    exit 0
fi

if [[ "$1" == "--namespace" ]] || [[ "$1" == "-n" ]]; then
    # variables
    namespace="$2"
    cluster=$(kubectl config current-context)

    statefulSets=$(kubectl get statefulsets -n $namespace -o jsonpath="{.items[*].metadata.name}")
    statefulSetArray=( $statefulSets )
    numOfStatefulSets=${#statefulSetArray[@]}
    podsInStatefulSets=$(kubectl get statefulsets -n $namespace -o jsonpath="{.items[*].status.replicas}")

    deployments=$(kubectl get deployments -n $namespace -o jsonpath="{.items[*].metadata.name}")
    deploymentArray=( $deployments )
    numOfDeployments=${#deploymentArray[@]}
    podsInDeployments=$(kubectl get deployments -n $namespace -o jsonpath="{.items[*].status.replicas}")

    daemonSets=$(kubectl get daemonsets -n $namespace -o jsonpath="{.items[*].metadata.name}")
    daemonSetArray=( $daemonSets )
    numOfDaemonsets=${#daemonSetArray[@]}
    podsInDaemonSets=$(kubectl get daemonsets -n $namespace -o jsonpath="{.items[*].status.desiredNumberScheduled}")

    pods=$(kubectl get pods -n $namespace -o jsonpath="{.items[*].metadata.name}")
    podArray=( $pods )
    numOfPods=${#podArray[@]}

    # sum up pods to be restarted
    totalRollingPods=0
    for i in ${podsInStatefulSets[@]}; do
    let totalRollingPods+=$i
    done
    for i in ${podsInDeployments[@]}; do
    let totalRollingPods+=$i
    done
    for i in ${podsInDaemonSets[@]}; do
    let totalRollingPods+=$i
    done

    # summary before run
    dateStart=$(date +'%a %b %d %r %Z %Y')
    summary="► Rolling namespace $namespace in cluster $cluster"
    echo "► Started: $dateStart"
    echo $summary
    echo "CAUTION: Switching contexts during the roll will interrupt the operation"

    # main run
    for i in $statefulSets; do
        kubectl -n $namespace rollout restart statefulset $i
    done

    for i in $deployments; do
        kubectl -n $namespace rollout restart deployment $i
    done

    for i in $daemonSets; do
        kubectl -n $namespace rollout restart daemonset $i
    done

    # conclusion summary
    dateEnd=$(date +'%a %b %d %r %Z %Y')
    if [[ "$numOfPods" == "$totalRollingPods" ]]; then
        echo "All pods in namespace $namespace were scheduled to be restarted"
    elif (( $numOfPods < $totalRollingPods )); then
        echo "ERROR: More pods were restarted than expected"
    else
        numMissedPods=$(( $numOfPods - $totalRollingPods ))
        echo "► WARNING: $numMissedPods pods in namespace $namespace were not restarted"
    fi
    echo "► Ended: $dateEnd"
    exit 0
fi

# message if nothing happened
echo "► WARNING: No action performed"
