version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1

jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  release:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: npm run release

workflows:
  build-test-release:
    jobs:
      - build
      - release:
          requires:
            - validate
            - lint
          filters:
            branches:
              only: master
